apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"YWxleGV1czc3OmdocF9tNkVQdm1SYTBWeWlsVWlxN3phTEhucHlrWXh4cTgxRnNmbXU="}}}'
type: kubernetes.io/dockerconfigjson
